//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AW.Data.DataService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdDto", Namespace="http://schemas.datacontract.org/2004/07/Service.Dto")]
    [System.SerializableAttribute()]
    public partial class AdDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ConditionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LocationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((this.CategoryIdField.Equals(value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ConditionId {
            get {
                return this.ConditionIdField;
            }
            set {
                if ((this.ConditionIdField.Equals(value) != true)) {
                    this.ConditionIdField = value;
                    this.RaisePropertyChanged("ConditionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LocationId {
            get {
                return this.LocationIdField;
            }
            set {
                if ((this.LocationIdField.Equals(value) != true)) {
                    this.LocationIdField = value;
                    this.RaisePropertyChanged("LocationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TypeId {
            get {
                return this.TypeIdField;
            }
            set {
                if ((this.TypeIdField.Equals(value) != true)) {
                    this.TypeIdField = value;
                    this.RaisePropertyChanged("TypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AdDetailsDto", Namespace="http://schemas.datacontract.org/2004/07/Service.Dto")]
    [System.SerializableAttribute()]
    public partial class AdDetailsDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConditionNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryName {
            get {
                return this.CategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNameField, value) != true)) {
                    this.CategoryNameField = value;
                    this.RaisePropertyChanged("CategoryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConditionName {
            get {
                return this.ConditionNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ConditionNameField, value) != true)) {
                    this.ConditionNameField = value;
                    this.RaisePropertyChanged("ConditionName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationName {
            get {
                return this.LocationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationNameField, value) != true)) {
                    this.LocationNameField = value;
                    this.RaisePropertyChanged("LocationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeName {
            get {
                return this.TypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeNameField, value) != true)) {
                    this.TypeNameField = value;
                    this.RaisePropertyChanged("TypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoryDto", Namespace="http://schemas.datacontract.org/2004/07/Service.Dto")]
    [System.SerializableAttribute()]
    public partial class CategoryDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CategoryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ParentCategoryIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CategoryId {
            get {
                return this.CategoryIdField;
            }
            set {
                if ((this.CategoryIdField.Equals(value) != true)) {
                    this.CategoryIdField = value;
                    this.RaisePropertyChanged("CategoryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryName {
            get {
                return this.CategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNameField, value) != true)) {
                    this.CategoryNameField = value;
                    this.RaisePropertyChanged("CategoryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ParentCategoryId {
            get {
                return this.ParentCategoryIdField;
            }
            set {
                if ((this.ParentCategoryIdField.Equals(value) != true)) {
                    this.ParentCategoryIdField = value;
                    this.RaisePropertyChanged("ParentCategoryId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConditionDto", Namespace="http://schemas.datacontract.org/2004/07/Service.Dto")]
    [System.SerializableAttribute()]
    public partial class ConditionDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ConditionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConditionNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ConditionId {
            get {
                return this.ConditionIdField;
            }
            set {
                if ((this.ConditionIdField.Equals(value) != true)) {
                    this.ConditionIdField = value;
                    this.RaisePropertyChanged("ConditionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConditionName {
            get {
                return this.ConditionNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ConditionNameField, value) != true)) {
                    this.ConditionNameField = value;
                    this.RaisePropertyChanged("ConditionName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TypeDto", Namespace="http://schemas.datacontract.org/2004/07/Service.Dto")]
    [System.SerializableAttribute()]
    public partial class TypeDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TypeId {
            get {
                return this.TypeIdField;
            }
            set {
                if ((this.TypeIdField.Equals(value) != true)) {
                    this.TypeIdField = value;
                    this.RaisePropertyChanged("TypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeName {
            get {
                return this.TypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeNameField, value) != true)) {
                    this.TypeNameField = value;
                    this.RaisePropertyChanged("TypeName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LocationDto", Namespace="http://schemas.datacontract.org/2004/07/Service.Dto")]
    [System.SerializableAttribute()]
    public partial class LocationDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LocationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LocationId {
            get {
                return this.LocationIdField;
            }
            set {
                if ((this.LocationIdField.Equals(value) != true)) {
                    this.LocationIdField = value;
                    this.RaisePropertyChanged("LocationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationName {
            get {
                return this.LocationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationNameField, value) != true)) {
                    this.LocationNameField = value;
                    this.RaisePropertyChanged("LocationName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDto", Namespace="http://schemas.datacontract.org/2004/07/Service.Dto")]
    [System.SerializableAttribute()]
    public partial class UserDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AW.Data.DataService.RoleDto RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AW.Data.DataService.RoleDto Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoleDto", Namespace="http://schemas.datacontract.org/2004/07/Service.Dto")]
    [System.SerializableAttribute()]
    public partial class RoleDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoleId {
            get {
                return this.RoleIdField;
            }
            set {
                if ((this.RoleIdField.Equals(value) != true)) {
                    this.RoleIdField = value;
                    this.RaisePropertyChanged("RoleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleName {
            get {
                return this.RoleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleNameField, value) != true)) {
                    this.RoleNameField = value;
                    this.RaisePropertyChanged("RoleName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhoneDto", Namespace="http://schemas.datacontract.org/2004/07/Service.Dto")]
    [System.SerializableAttribute()]
    public partial class PhoneDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PhoneIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PhoneId {
            get {
                return this.PhoneIdField;
            }
            set {
                if ((this.PhoneIdField.Equals(value) != true)) {
                    this.PhoneIdField = value;
                    this.RaisePropertyChanged("PhoneId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmailDto", Namespace="http://schemas.datacontract.org/2004/07/Service.Dto")]
    [System.SerializableAttribute()]
    public partial class EmailDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EmailIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EmailId {
            get {
                return this.EmailIdField;
            }
            set {
                if ((this.EmailIdField.Equals(value) != true)) {
                    this.EmailIdField = value;
                    this.RaisePropertyChanged("EmailId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailValue {
            get {
                return this.EmailValueField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailValueField, value) != true)) {
                    this.EmailValueField = value;
                    this.RaisePropertyChanged("EmailValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataService.IDataService")]
    public interface IDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/CreateAdDto", ReplyAction="http://tempuri.org/IDataService/CreateAdDtoResponse")]
        void CreateAdDto(AW.Data.DataService.AdDto adDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/CreateAdDto", ReplyAction="http://tempuri.org/IDataService/CreateAdDtoResponse")]
        System.Threading.Tasks.Task CreateAdDtoAsync(AW.Data.DataService.AdDto adDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/EditeAdDto", ReplyAction="http://tempuri.org/IDataService/EditeAdDtoResponse")]
        void EditeAdDto(AW.Data.DataService.AdDto adDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/EditeAdDto", ReplyAction="http://tempuri.org/IDataService/EditeAdDtoResponse")]
        System.Threading.Tasks.Task EditeAdDtoAsync(AW.Data.DataService.AdDto adDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/DeleteAdDto", ReplyAction="http://tempuri.org/IDataService/DeleteAdDtoResponse")]
        void DeleteAdDto(int adId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/DeleteAdDto", ReplyAction="http://tempuri.org/IDataService/DeleteAdDtoResponse")]
        System.Threading.Tasks.Task DeleteAdDtoAsync(int adId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetAdsDto", ReplyAction="http://tempuri.org/IDataService/GetAdsDtoResponse")]
        System.Collections.Generic.List<AW.Data.DataService.AdDto> GetAdsDto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetAdsDto", ReplyAction="http://tempuri.org/IDataService/GetAdsDtoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<AW.Data.DataService.AdDto>> GetAdsDtoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetAdsByCategoryDto", ReplyAction="http://tempuri.org/IDataService/GetAdsByCategoryDtoResponse")]
        System.Collections.Generic.List<AW.Data.DataService.AdDto> GetAdsByCategoryDto(int categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetAdsByCategoryDto", ReplyAction="http://tempuri.org/IDataService/GetAdsByCategoryDtoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<AW.Data.DataService.AdDto>> GetAdsByCategoryDtoAsync(int categoryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetAdDetailsDto", ReplyAction="http://tempuri.org/IDataService/GetAdDetailsDtoResponse")]
        AW.Data.DataService.AdDetailsDto GetAdDetailsDto(int adId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetAdDetailsDto", ReplyAction="http://tempuri.org/IDataService/GetAdDetailsDtoResponse")]
        System.Threading.Tasks.Task<AW.Data.DataService.AdDetailsDto> GetAdDetailsDtoAsync(int adId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetCategoriesDto", ReplyAction="http://tempuri.org/IDataService/GetCategoriesDtoResponse")]
        System.Collections.Generic.List<AW.Data.DataService.CategoryDto> GetCategoriesDto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetCategoriesDto", ReplyAction="http://tempuri.org/IDataService/GetCategoriesDtoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<AW.Data.DataService.CategoryDto>> GetCategoriesDtoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetConditionsDto", ReplyAction="http://tempuri.org/IDataService/GetConditionsDtoResponse")]
        System.Collections.Generic.List<AW.Data.DataService.ConditionDto> GetConditionsDto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetConditionsDto", ReplyAction="http://tempuri.org/IDataService/GetConditionsDtoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<AW.Data.DataService.ConditionDto>> GetConditionsDtoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetTypesDto", ReplyAction="http://tempuri.org/IDataService/GetTypesDtoResponse")]
        System.Collections.Generic.List<AW.Data.DataService.TypeDto> GetTypesDto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetTypesDto", ReplyAction="http://tempuri.org/IDataService/GetTypesDtoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<AW.Data.DataService.TypeDto>> GetTypesDtoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetLocationsDto", ReplyAction="http://tempuri.org/IDataService/GetLocationsDtoResponse")]
        System.Collections.Generic.List<AW.Data.DataService.LocationDto> GetLocationsDto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetLocationsDto", ReplyAction="http://tempuri.org/IDataService/GetLocationsDtoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<AW.Data.DataService.LocationDto>> GetLocationsDtoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/CreateUserDto", ReplyAction="http://tempuri.org/IDataService/CreateUserDtoResponse")]
        void CreateUserDto(AW.Data.DataService.UserDto userDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/CreateUserDto", ReplyAction="http://tempuri.org/IDataService/CreateUserDtoResponse")]
        System.Threading.Tasks.Task CreateUserDtoAsync(AW.Data.DataService.UserDto userDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/EditeUserDto", ReplyAction="http://tempuri.org/IDataService/EditeUserDtoResponse")]
        void EditeUserDto(AW.Data.DataService.UserDto userDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/EditeUserDto", ReplyAction="http://tempuri.org/IDataService/EditeUserDtoResponse")]
        System.Threading.Tasks.Task EditeUserDtoAsync(AW.Data.DataService.UserDto userDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/EditePasswordDto", ReplyAction="http://tempuri.org/IDataService/EditePasswordDtoResponse")]
        void EditePasswordDto(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/EditePasswordDto", ReplyAction="http://tempuri.org/IDataService/EditePasswordDtoResponse")]
        System.Threading.Tasks.Task EditePasswordDtoAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/DeleteUserDto", ReplyAction="http://tempuri.org/IDataService/DeleteUserDtoResponse")]
        void DeleteUserDto(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/DeleteUserDto", ReplyAction="http://tempuri.org/IDataService/DeleteUserDtoResponse")]
        System.Threading.Tasks.Task DeleteUserDtoAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetUsersDto", ReplyAction="http://tempuri.org/IDataService/GetUsersDtoResponse")]
        System.Collections.Generic.List<AW.Data.DataService.UserDto> GetUsersDto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetUsersDto", ReplyAction="http://tempuri.org/IDataService/GetUsersDtoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<AW.Data.DataService.UserDto>> GetUsersDtoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetUserDtoByName", ReplyAction="http://tempuri.org/IDataService/GetUserDtoByNameResponse")]
        AW.Data.DataService.UserDto GetUserDtoByName(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetUserDtoByName", ReplyAction="http://tempuri.org/IDataService/GetUserDtoByNameResponse")]
        System.Threading.Tasks.Task<AW.Data.DataService.UserDto> GetUserDtoByNameAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/IsValidUser", ReplyAction="http://tempuri.org/IDataService/IsValidUserResponse")]
        bool IsValidUser(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/IsValidUser", ReplyAction="http://tempuri.org/IDataService/IsValidUserResponse")]
        System.Threading.Tasks.Task<bool> IsValidUserAsync(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetRolesDto", ReplyAction="http://tempuri.org/IDataService/GetRolesDtoResponse")]
        System.Collections.Generic.List<AW.Data.DataService.RoleDto> GetRolesDto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetRolesDto", ReplyAction="http://tempuri.org/IDataService/GetRolesDtoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<AW.Data.DataService.RoleDto>> GetRolesDtoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetPhonesDto", ReplyAction="http://tempuri.org/IDataService/GetPhonesDtoResponse")]
        System.Collections.Generic.List<AW.Data.DataService.PhoneDto> GetPhonesDto(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetPhonesDto", ReplyAction="http://tempuri.org/IDataService/GetPhonesDtoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<AW.Data.DataService.PhoneDto>> GetPhonesDtoAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/CreatePhoneDto", ReplyAction="http://tempuri.org/IDataService/CreatePhoneDtoResponse")]
        void CreatePhoneDto(AW.Data.DataService.PhoneDto phoneDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/CreatePhoneDto", ReplyAction="http://tempuri.org/IDataService/CreatePhoneDtoResponse")]
        System.Threading.Tasks.Task CreatePhoneDtoAsync(AW.Data.DataService.PhoneDto phoneDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/EditePhoneDto", ReplyAction="http://tempuri.org/IDataService/EditePhoneDtoResponse")]
        void EditePhoneDto(AW.Data.DataService.PhoneDto phoneDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/EditePhoneDto", ReplyAction="http://tempuri.org/IDataService/EditePhoneDtoResponse")]
        System.Threading.Tasks.Task EditePhoneDtoAsync(AW.Data.DataService.PhoneDto phoneDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/DeletePhoneDto", ReplyAction="http://tempuri.org/IDataService/DeletePhoneDtoResponse")]
        void DeletePhoneDto(int phoneId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/DeletePhoneDto", ReplyAction="http://tempuri.org/IDataService/DeletePhoneDtoResponse")]
        System.Threading.Tasks.Task DeletePhoneDtoAsync(int phoneId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetEmailsDto", ReplyAction="http://tempuri.org/IDataService/GetEmailsDtoResponse")]
        System.Collections.Generic.List<AW.Data.DataService.EmailDto> GetEmailsDto(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/GetEmailsDto", ReplyAction="http://tempuri.org/IDataService/GetEmailsDtoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<AW.Data.DataService.EmailDto>> GetEmailsDtoAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/CreateEmailDto", ReplyAction="http://tempuri.org/IDataService/CreateEmailDtoResponse")]
        void CreateEmailDto(AW.Data.DataService.EmailDto emailDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/CreateEmailDto", ReplyAction="http://tempuri.org/IDataService/CreateEmailDtoResponse")]
        System.Threading.Tasks.Task CreateEmailDtoAsync(AW.Data.DataService.EmailDto emailDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/EditeEmailDto", ReplyAction="http://tempuri.org/IDataService/EditeEmailDtoResponse")]
        void EditeEmailDto(AW.Data.DataService.EmailDto emailDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/EditeEmailDto", ReplyAction="http://tempuri.org/IDataService/EditeEmailDtoResponse")]
        System.Threading.Tasks.Task EditeEmailDtoAsync(AW.Data.DataService.EmailDto emailDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/DeleteEmailDto", ReplyAction="http://tempuri.org/IDataService/DeleteEmailDtoResponse")]
        void DeleteEmailDto(int emailId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataService/DeleteEmailDto", ReplyAction="http://tempuri.org/IDataService/DeleteEmailDtoResponse")]
        System.Threading.Tasks.Task DeleteEmailDtoAsync(int emailId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataServiceChannel : AW.Data.DataService.IDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceClient : System.ServiceModel.ClientBase<AW.Data.DataService.IDataService>, AW.Data.DataService.IDataService {
        
        public DataServiceClient() {
        }
        
        public DataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CreateAdDto(AW.Data.DataService.AdDto adDto) {
            base.Channel.CreateAdDto(adDto);
        }
        
        public System.Threading.Tasks.Task CreateAdDtoAsync(AW.Data.DataService.AdDto adDto) {
            return base.Channel.CreateAdDtoAsync(adDto);
        }
        
        public void EditeAdDto(AW.Data.DataService.AdDto adDto) {
            base.Channel.EditeAdDto(adDto);
        }
        
        public System.Threading.Tasks.Task EditeAdDtoAsync(AW.Data.DataService.AdDto adDto) {
            return base.Channel.EditeAdDtoAsync(adDto);
        }
        
        public void DeleteAdDto(int adId) {
            base.Channel.DeleteAdDto(adId);
        }
        
        public System.Threading.Tasks.Task DeleteAdDtoAsync(int adId) {
            return base.Channel.DeleteAdDtoAsync(adId);
        }
        
        public System.Collections.Generic.List<AW.Data.DataService.AdDto> GetAdsDto() {
            return base.Channel.GetAdsDto();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<AW.Data.DataService.AdDto>> GetAdsDtoAsync() {
            return base.Channel.GetAdsDtoAsync();
        }
        
        public System.Collections.Generic.List<AW.Data.DataService.AdDto> GetAdsByCategoryDto(int categoryId) {
            return base.Channel.GetAdsByCategoryDto(categoryId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<AW.Data.DataService.AdDto>> GetAdsByCategoryDtoAsync(int categoryId) {
            return base.Channel.GetAdsByCategoryDtoAsync(categoryId);
        }
        
        public AW.Data.DataService.AdDetailsDto GetAdDetailsDto(int adId) {
            return base.Channel.GetAdDetailsDto(adId);
        }
        
        public System.Threading.Tasks.Task<AW.Data.DataService.AdDetailsDto> GetAdDetailsDtoAsync(int adId) {
            return base.Channel.GetAdDetailsDtoAsync(adId);
        }
        
        public System.Collections.Generic.List<AW.Data.DataService.CategoryDto> GetCategoriesDto() {
            return base.Channel.GetCategoriesDto();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<AW.Data.DataService.CategoryDto>> GetCategoriesDtoAsync() {
            return base.Channel.GetCategoriesDtoAsync();
        }
        
        public System.Collections.Generic.List<AW.Data.DataService.ConditionDto> GetConditionsDto() {
            return base.Channel.GetConditionsDto();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<AW.Data.DataService.ConditionDto>> GetConditionsDtoAsync() {
            return base.Channel.GetConditionsDtoAsync();
        }
        
        public System.Collections.Generic.List<AW.Data.DataService.TypeDto> GetTypesDto() {
            return base.Channel.GetTypesDto();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<AW.Data.DataService.TypeDto>> GetTypesDtoAsync() {
            return base.Channel.GetTypesDtoAsync();
        }
        
        public System.Collections.Generic.List<AW.Data.DataService.LocationDto> GetLocationsDto() {
            return base.Channel.GetLocationsDto();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<AW.Data.DataService.LocationDto>> GetLocationsDtoAsync() {
            return base.Channel.GetLocationsDtoAsync();
        }
        
        public void CreateUserDto(AW.Data.DataService.UserDto userDto) {
            base.Channel.CreateUserDto(userDto);
        }
        
        public System.Threading.Tasks.Task CreateUserDtoAsync(AW.Data.DataService.UserDto userDto) {
            return base.Channel.CreateUserDtoAsync(userDto);
        }
        
        public void EditeUserDto(AW.Data.DataService.UserDto userDto) {
            base.Channel.EditeUserDto(userDto);
        }
        
        public System.Threading.Tasks.Task EditeUserDtoAsync(AW.Data.DataService.UserDto userDto) {
            return base.Channel.EditeUserDtoAsync(userDto);
        }
        
        public void EditePasswordDto(string userName, string password) {
            base.Channel.EditePasswordDto(userName, password);
        }
        
        public System.Threading.Tasks.Task EditePasswordDtoAsync(string userName, string password) {
            return base.Channel.EditePasswordDtoAsync(userName, password);
        }
        
        public void DeleteUserDto(string userName) {
            base.Channel.DeleteUserDto(userName);
        }
        
        public System.Threading.Tasks.Task DeleteUserDtoAsync(string userName) {
            return base.Channel.DeleteUserDtoAsync(userName);
        }
        
        public System.Collections.Generic.List<AW.Data.DataService.UserDto> GetUsersDto() {
            return base.Channel.GetUsersDto();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<AW.Data.DataService.UserDto>> GetUsersDtoAsync() {
            return base.Channel.GetUsersDtoAsync();
        }
        
        public AW.Data.DataService.UserDto GetUserDtoByName(string userName) {
            return base.Channel.GetUserDtoByName(userName);
        }
        
        public System.Threading.Tasks.Task<AW.Data.DataService.UserDto> GetUserDtoByNameAsync(string userName) {
            return base.Channel.GetUserDtoByNameAsync(userName);
        }
        
        public bool IsValidUser(string userName, string password) {
            return base.Channel.IsValidUser(userName, password);
        }
        
        public System.Threading.Tasks.Task<bool> IsValidUserAsync(string userName, string password) {
            return base.Channel.IsValidUserAsync(userName, password);
        }
        
        public System.Collections.Generic.List<AW.Data.DataService.RoleDto> GetRolesDto() {
            return base.Channel.GetRolesDto();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<AW.Data.DataService.RoleDto>> GetRolesDtoAsync() {
            return base.Channel.GetRolesDtoAsync();
        }
        
        public System.Collections.Generic.List<AW.Data.DataService.PhoneDto> GetPhonesDto(string userName) {
            return base.Channel.GetPhonesDto(userName);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<AW.Data.DataService.PhoneDto>> GetPhonesDtoAsync(string userName) {
            return base.Channel.GetPhonesDtoAsync(userName);
        }
        
        public void CreatePhoneDto(AW.Data.DataService.PhoneDto phoneDto) {
            base.Channel.CreatePhoneDto(phoneDto);
        }
        
        public System.Threading.Tasks.Task CreatePhoneDtoAsync(AW.Data.DataService.PhoneDto phoneDto) {
            return base.Channel.CreatePhoneDtoAsync(phoneDto);
        }
        
        public void EditePhoneDto(AW.Data.DataService.PhoneDto phoneDto) {
            base.Channel.EditePhoneDto(phoneDto);
        }
        
        public System.Threading.Tasks.Task EditePhoneDtoAsync(AW.Data.DataService.PhoneDto phoneDto) {
            return base.Channel.EditePhoneDtoAsync(phoneDto);
        }
        
        public void DeletePhoneDto(int phoneId) {
            base.Channel.DeletePhoneDto(phoneId);
        }
        
        public System.Threading.Tasks.Task DeletePhoneDtoAsync(int phoneId) {
            return base.Channel.DeletePhoneDtoAsync(phoneId);
        }
        
        public System.Collections.Generic.List<AW.Data.DataService.EmailDto> GetEmailsDto(string userName) {
            return base.Channel.GetEmailsDto(userName);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<AW.Data.DataService.EmailDto>> GetEmailsDtoAsync(string userName) {
            return base.Channel.GetEmailsDtoAsync(userName);
        }
        
        public void CreateEmailDto(AW.Data.DataService.EmailDto emailDto) {
            base.Channel.CreateEmailDto(emailDto);
        }
        
        public System.Threading.Tasks.Task CreateEmailDtoAsync(AW.Data.DataService.EmailDto emailDto) {
            return base.Channel.CreateEmailDtoAsync(emailDto);
        }
        
        public void EditeEmailDto(AW.Data.DataService.EmailDto emailDto) {
            base.Channel.EditeEmailDto(emailDto);
        }
        
        public System.Threading.Tasks.Task EditeEmailDtoAsync(AW.Data.DataService.EmailDto emailDto) {
            return base.Channel.EditeEmailDtoAsync(emailDto);
        }
        
        public void DeleteEmailDto(int emailId) {
            base.Channel.DeleteEmailDto(emailId);
        }
        
        public System.Threading.Tasks.Task DeleteEmailDtoAsync(int emailId) {
            return base.Channel.DeleteEmailDtoAsync(emailId);
        }
    }
}
